name: daredevil
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch
    - torchaudio
    - speechbrain
    - librosa
    - sounddevice
    - soundfile
    - matplotlib
    - cryptography
    - mcp
    - pytest
    - -e .
