"""Synthetic 'crowd' — labeled babble for the *pick me out of the crowd* demo.

The onboarding reveal needs a room full of *other* people talking so the system can
prove it still finds YOU. We do not ship recordings or real voices (privacy, rule #6
no third-party names, rule #7 honest/labeled): this is a murmur of **distinct
synthetic speakers**, generated by the same speech-like DSP the rest of the demo
uses, clearly SYNTHETIC. Two ways to use it:

* ``crowd_scene_sources()`` — UNKNOWN talkers to drop into a synthetic ``listen()``
  next to you (works anywhere, no hardware).
* ``CrowdPlayer`` — loops the babble out the **speakers** during a live session, so
  the mic genuinely hears you *over a crowd* and the SPRT has to earn the match.
  Playback is optional (sounddevice); with none, it's an honest no-op.

Local only. Nothing here touches the network.
"""
from __future__ import annotations

import logging
import random
from typing import List, Optional

from .capture import _synth_source  # the project's speech-like synth (same one the demo uses)

log = logging.getLogger("daredevil.crowd")

# Generic crowd labels — never a real person's name (rule #6). Different labels give
# different synthetic pitches/formants, so the crowd is a set of distinct "voices".
CROWD_NAMES = ["voice-1", "voice-2", "voice-3", "voice-4", "voice-5", "voice-6"]


def babble(n_speakers: int = 4, seconds: float = 4.0, sr: int = 16000,
           seed: int = 0, gain: float = 0.55) -> List[float]:
    """A mono murmur of ``n_speakers`` overlapping synthetic talkers (SYNTHETIC)."""
    n_speakers = max(1, n_speakers)
    n = int(seconds * sr)
    rng = random.Random(seed)
    mix = [0.0] * n
    max_off = int(0.3 * sr)
    for k in range(n_speakers):
        # generate a little longer than needed so every desync offset stays in-bounds
        sig = _synth_source(f"crowd-{seed}-{k}", "speech", seconds + 0.5, sr)
        off = rng.randint(0, max_off)  # stagger starts so it reads as overlapping talk
        for i in range(n):
            j = i + off
            if j < len(sig):
                mix[i] += sig[j]
    peak = max((abs(v) for v in mix), default=1.0) or 1.0
    return [max(-1.0, min(1.0, (v / peak) * gain)) for v in mix]


def crowd_scene_sources(n_speakers: int = 4, base_azimuth: float = 90.0,
                        distress: float = 0.05) -> List[dict]:
    """Scene specs for UNKNOWN talkers, spread around you — for a synthetic ``listen``.

    These ride alongside your enrolled source so the router has to surface *you* and
    gate *them* out. Real recognition (cosine SPRT) does the work; nothing is faked.
    """
    out = []
    for k in range(max(1, n_speakers)):
        out.append({
            "name": CROWD_NAMES[k % len(CROWD_NAMES)] if k < len(CROWD_NAMES) else f"voice-{k+1}",
            "enrolled": False, "class": "speech",
            "azimuth": float((base_azimuth + k * 47) % 360), "elevation": 0.0,
            "prosody_state": "calm", "distress": distress,
        })
    return out


class CrowdPlayer:
    """Loop synthetic babble out the speakers for the live 'against the crowd' reveal.

    Use as a context manager. If sounddevice/numpy aren't present it does nothing
    (``available == False``) and the caller falls back to the synthetic-scene crowd —
    no silent pretending that a crowd is playing when it isn't.
    """

    def __init__(self, n_speakers: int = 4, sr: int = 16000, gain: float = 0.55, seed: int = 0):
        self.n_speakers = n_speakers
        self.sr = sr
        self.gain = gain
        self.seed = seed
        self.available = False
        self._buf: Optional[list] = None

    def __enter__(self) -> "CrowdPlayer":
        return self.start()

    def __exit__(self, *exc) -> None:
        self.stop()

    def start(self) -> "CrowdPlayer":
        try:
            import sounddevice as sd
            import numpy as np
        except Exception:
            log.info("crowd playback unavailable (no sounddevice/numpy) — using the "
                     "synthetic-scene crowd instead")
            return self
        try:
            self._buf = babble(self.n_speakers, 4.0, self.sr, self.seed, self.gain)
            arr = np.asarray(self._buf, dtype="float32")
            sd.play(arr, self.sr, loop=True)  # non-blocking; PortAudio loops it
            self.available = True
        except Exception as e:  # device busy / no output — stay honest, don't crash the demo
            log.warning("could not start crowd playback: %s", e)
            self.available = False
        return self

    def stop(self) -> None:
        if not self.available:
            return
        try:
            import sounddevice as sd
            sd.stop()
        except Exception:
            pass
        self.available = False
